name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant

    - name: Install Node.js (for SonarScanner)
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install SonarScanner via npm
      run: npm install sonarqube-scanner

    - name: Build with Ant (Compile)
      run: ant compile  # Compile the full project

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
      -Dsonar.projectKey=mariakalafati_tomcat \
      -Dsonar.organization=mariakalafati \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.sources=. \
      -Dsonar.language=java \
      -Dsonar.java.binaries=output/classes \
      -Dsonar.c.file.suffixes=- \
      -Dsonar.cpp.file.suffixes=- \
      -Dsonar.objc.file.suffixes=-
