name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ant unzip

    - name: Install SonarScanner
      run: |
        curl -fsSL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-5.0.1.3006-linux.zip -o sonar-scanner.zip
        unzip sonar-scanner.zip -d /opt
        sudo mv /opt/sonar-scanner-* /opt/sonar-scanner
        export PATH=$PATH:/opt/sonar-scanner/bin

    - name: Build with Ant (Compile)
      run: ant compile  # Compile your Java project using Ant

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=mariakalafati_tomcat \
          -Dsonar.organization=mariakalafati \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=. \
          -Dsonar.language=java \
          -Dsonar.java.binaries=output/classes \
          -Dsonar.c.file.suffixes=- \
          -Dsonar.cpp.file.suffixes=- \
          -Dsonar.objc.file.suffixes=-
