name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant

    - name: Install SonarScanner
      run: |
        sudo apt-get install -y unzip
        wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-5.0.1.3006-linux.zip
        unzip sonar-scanner.zip
        sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
        echo "export PATH=$PATH:/opt/sonar-scanner/bin" >> $HOME/.bashrc
        echo "export PATH=$PATH:/opt/sonar-scanner/bin" >> $GITHUB_ENV
        source $HOME/.bashrc

    - name: Build with Ant (Compile)
      run: ant compile  # Use the 'compile' target to compile the project

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=mariakalafati_tomcat \
          -Dsonar.organization=mariakalafati \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=./test/webapp-virtual-webapp/src,./webapps/docs/appdev/sample/src,./modules/owb/src,./modules/jdbc-pool/src,./modules/cxf/src \
          -Dsonar.language=java \
          -Dsonar.java.binaries=output/classes  # Change this if your compiled files are elsewhere
